# Generated by Django 4.0 on 2023-02-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0002_house_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
