# Generated by Django 4.0 on 2023-02-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0009_alter_house_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
