# Generated by Django 4.0 on 2023-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0013_remove_house_user_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='purpose',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], default='For Rent', max_length=200, null=True),
        ),
    ]
