# Generated by Django 4.1.7 on 2023-03-18 21:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0019_alter_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
