# Generated by Django 4.1.7 on 2023-03-18 21:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0020_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
