# Generated by Django 4.1.7 on 2023-03-18 22:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0021_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
