# Generated by Django 4.1.7 on 2023-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0023_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
