# Generated by Django 4.1.7 on 2023-03-19 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0026_ownermessage_tenantmessage_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenantmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
