# Generated by Django 4.1.7 on 2023-06-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0030_ownermessage_owner_tenantmessage_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='video',
            field=models.FileField(default=None, upload_to='images/%y'),
        ),
    ]
