# Generated by Django 4.1.7 on 2023-06-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0031_house_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
